### ISSUE TITLE
Clarification on Prediction Scores

### ISSUE THREAD

**Issue by vm7608** [jerpelhan/GeCo#1]
First of all, thank you for your work on this model! It's one of the best few-shot models I've used.

I'm a bit confused about the prediction scores returned by `model(img, boxes)` in
https://github.com/jerpelhan/GeCo/blob/d91de59428d7658c5365da5936fab6a5763b5666/demo.py#L91

The output dictionary has the keys `dict_keys(['pred_boxes', 'box_v', 'scores'])`. In the code, `outputs[idx]["box_v"]` is used for NMS.

https://github.com/jerpelhan/GeCo/blob/d91de59428d7658c5365da5936fab6a5763b5666/demo.py#L95-L96

Could you please clarify the following:

* What is the meaning of `outputs[idx]["box_v"]`?
* What is the meaning of `outputs[idx]["scores"]`?
* Which of these should I use to filter output boxes based on a confidence threshold?

Again, thank you so much!

**Comment by jerpelhan** [comment]
Thank you! We’re thrilled to hear you like our work!

To clarify, we indeed use two different scoring functions:
	1.	box_v: This score is predicted by our model and reflects the confidence for the correct object class.
	2.	scores: This represents the IoU prediction of the SAM model and is used exclusively during evaluation for calculating the detection score.

For practical applications, I recommend combining both scores. The SAM score is class-independent and indicates how well the bounding box fits an arbitrary object. Meanwhile, the score from our model captures class-specific confidence. Combining these can provide a more robust overall scoring mechanism.

**Comment by jerpelhan** [comment]
1. Yes, box_v can indeed be greater than one. We observed that using a sigmoid activation at the end negatively impacted performance.

2. The division (e.g., max_response/4) is used to establish a threshold. We found it worked best on the FSCD validation set.

3. An educated guess for combining the scores would be to use a weighted average, with a higher weight assigned to the box_v value.
